name: Daily Python Script

on:
  schedule:
    - cron: '0 15 * * *' # This schedules the workflow to run every day at midnight (UTC)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Specify the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt # If you have any Python dependencies, specify them in requirements.txt

      - name: Run Python Script
        run: python project.py # Replace 'your_script.py' with the name of your Python script
