name: Daily Python Script

on:
  schedule:
    - cron: '0 15 * * *' # This schedules the workflow to run every day at midnight (UTC)
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the Secret
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > google-credentials.json
          if [ -s "google-credentials.json" ]; then
              gcloud auth activate-service-account --key-file=google-credentials.json
          else
            echo "Error: google-credentials.json is empty or not found."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Specify the Python version you need

      - name: Install dependencies
        run: pip install gspread oauth2client

     
      - name: Run Python Script
        run: python project.py # Replace 'your_script.py' with the name of your Python script
