name: Daily Python Script

on:
  schedule:
    - cron: '0 15 * * *' # This schedules the workflow to run every day at midnight (UTC)
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Specify the Python version you need

      - name: Install dependencies
        run: pip install gspread oauth2client

     
      - name: Read Google Credentials
        run: echo "$(<google-credentials.json)" > credentials.json

      - name: Run Python Script
        run: |
          cat credentials.json  # Check the content of credentials.json (for debugging purposes)
          python project.py
